name: check_Ipynb

on:
  pull_request:
    branches: [ master, main ]
    types: [opened, synchronize, reopened, edited]

  workflow_dispatch:

jobs:
  check-lab-number:
  # проверка на название pull request
  # Можно добавлять labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo ${{github.event.pull_request.title}}
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
