name: check_Ipynb

on:
  pull_request:
    branches: [ master, main ]
    types: [opened, synchronize, reopened, edited]

  workflow_dispatch:


jobs:
  check_and_update_ipynb:
  # проверка на название pull request
  # Можно добавлять labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Имя PR
        run: echo ${{github.event.pull_request.title}}
      - name: Тест питона
        run: |
          python3 << END
          import os
          pr_name = '${{github.event.pull_request.title}}'
          index = pr_name.rfind('_')
          print(pr_name[:index]+'/'+pr_name[index+1:]+'.ipynb')
          END
      - name: test1
        run: | 
          echo $PATH_TO_LAB
          echo $FILE_NAME
      - name: test
        run: ls
